version: '3.8'

services:
  # --- Infrastructure ---
  postgres:
    image: postgres:14-alpine
    volumes: [postgres_data:/var/lib/postgresql/data/]
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    ports: ["5432:5432"]

  redis:
    image: redis:7-alpine
    volumes: [redis_data:/data]

  # --- Backend Services ---
  api_gateway:
    build: ./backend/api_gateway
    ports: ["8000:8000"]
    env_file: ./backend/.env
    depends_on: [economic_service, sentiment_service, technicals_service, cross_asset_service]

  economic_service:
    build: ./backend/services/economic_service
    env_file: ./backend/.env
    depends_on: [redis]

  sentiment_service:
    build: ./backend/services/sentiment_service
    env_file: ./backend/.env
    depends_on: [redis]

  technicals_service:
    build: ./backend/services/technicals_service
    env_file: ./backend/.env
    depends_on: [redis]

  cross_asset_service:
    build: ./backend/services/cross_asset_service
    env_file: ./backend/.env
    depends_on: [redis]

  scheduler:
    build: ./backend/scheduler
    env_file: ./backend/.env
    depends_on: [economic_service, sentiment_service, technicals_service, cross_asset_service]

  # --- Frontend ---
  frontend:
    build: ./frontend
    ports: ["5173:5173"]
    volumes: ["./frontend:/app", "/app/node_modules"]
    environment:
      - VITE_API_BASE_URL=http://localhost:8000
      - VITE_API_KEY=${API_KEY}
    depends_on: [api_gateway]

volumes:
  postgres_data:
  redis_data:
